import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AutoNotifications from "./components/AutoNotifications";
import AutoUserMessages from "./components/AutoUserMessages";
import { PaymentProvider } from "./components/payment/PaymentContext";
import { Suspense } from "react";
import gtmBody from "./scripts/gtm-body";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div dangerouslySetInnerHTML={{ __html: gtmBody }} />
       <Suspense>
        <PaymentProvider>
          {children}
          <AutoNotifications />
          <AutoUserMessages />
        </PaymentProvider>
        </Suspense>
      </body>
    </html>
  );
}
